name: Tests
on:
  - push
  - pull_request
jobs:
  tests:
    name: ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: 3.8, os: ubuntu-latest }
          - { python-version: 3.7, os: ubuntu-latest }
          - { python-version: 3.6, os: ubuntu-latest }
          - { python-version: 3.8, os: windows-latest }
          - { python-version: 3.8, os: macos-latest }

    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-python@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install nox==2020.5.24
      - run: pip install poetry==1.0.9
      - run: nox
